---
- name: Installation Apache
  hosts: webservers

  tasks:
    - name: Refresh cache and install Apache2
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: Custom index.html
      ansible.builtin.copy:
        dest: "/var/www/html/index.html"
        owner: www-data
        group: www-data
        mode: '0755'
        content: |
          Custom Web Page !!!

    - name: Apache2 enabled
      ansible.builtin.service:
        name: apache2
        enabled: true
        state: started

